chore: added more hba1c NPU codes to the fake dataset
steno-aarhus/osdc pull request #102
Opened 2024-05-16 10:20 UTC by lwjohnst86

These codes are for HbA1c, so want to inflate the number of values within the fake data

2024-05-16 11:13 UTC, signekb approved these changes
Nice 🎉

2024-05-17 22:43 UTC, Aastedet requested changes
Small edit to make mutated rows a mix of 27300 and 03835, instead of only-27300 or only-03835 depending on the random seed.

2024-05-17 22:43 UTC, Aastedet commented on data-raw/simulate-data.R
> +          sample(c("NPU27300", "NPU03835"), 1),
```suggestion
          sample(c("NPU27300", "NPU03835"), dplyr::n(), replace = TRUE),
```

2024-05-18 13:47 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +          sample(c("NPU27300", "NPU03835"), 1),
Nice catch!

2024-05-18 13:47 UTC, merged