Patch make generated padded integers useful for joining
steno-aarhus/osdc pull request #170
Opened 2024-12-19 13:45 UTC by Aastedet

By setting the random seed to `length`, generated integers of the same length are made identical. This allows the synthetic data to be used for joining by id variables like pnr, cpr, recnum and dw_ek_kontakt.

2024-12-19 13:52 UTC, lwjohnst86 requested changes
Ah! @signekb was asking about and figuring out the same issue with seeds. I think setting the seed in the targets pipeline might be better for overall reproducibility, so maybe remove the code?

2024-12-19 13:54 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @param length An integer determining the length of the padded integer. Generated integers of the same length are identical to facilitate joining by pnr, cpr, recnum and dw_ek_kontakt.
The added text could be moved up into the roxygen description section (as a new paragraph below the title).

2024-12-19 13:55 UTC, signekb commented
> Ah! @signekb was asking about and figuring out the same issue with seeds. I think setting the seed in the targets pipeline might be better for overall reproducibility, so maybe remove the code?

I'm on it 💪

2024-12-19 14:24 UTC, Aastedet commented
I converted this back to a draft. I'll pick it up once #167 is merged and see what needs using.

2024-12-20 08:47 UTC, Aastedet commented
Seems like this PR is still needed after #167. Verify that the same values of e.g. `recnum` are in both `lpr_adm` and `lpr_diag`:

`register_data$lpr_diag$recnum[register_data$lpr_diag$recnum %in% register_data$lpr_adm$recnum]` should return something. I'll update this draft with suggestions from @lwjohnst86 and convert to PR.

2024-12-20 10:52 UTC, signekb commented on data-raw/simulate-data.R
> +  set.seed(length)
Why length? Couldn't the seed be 123?

2024-12-20 10:55 UTC, signekb commented on data-raw/simulate-data.R
> +  set.seed(length)
Is it an issue to set a seed inside a function? 
Is it an issue to set a seed here "locally" and also globally in the pipeline?

2024-12-20 11:40 UTC, Aastedet commented on data-raw/simulate-data.R
> +  set.seed(length)
It could be, that should also work.

2024-12-20 12:00 UTC, signekb commented
Just writing some points down from our talk,@Aastedet:

The issue here is that for us to be able to join the simulated data from the different data sources in a meaningful way, we need an overlap in the variables we join by. This includes the variables, amongst others, `recnum` and `pnr`. 

So, a suggested solution for this is to set a seed *in* the functions that create these random padded numbers, so the seed will be reset every time the function is run. This way, we ensure that the same padded integers will be created across data sources. 

@lwjohnst86 What's your thoughts on this? :)

2025-02-05 07:53 UTC, lwjohnst86 approved these changes
I think we can test this out and see if it works. I don't actually know, so :shrug:

2025-02-05 07:53 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +  set.seed(length)
Hmm good question. I'm not sure. If it generates the necessary integers, than I guess so! Let's try it out. It is after all, only for the fake data generation.

2025-02-05 08:52 UTC, merged