Docs/add doc to simulate data
steno-aarhus/osdc pull request #80
Opened 2024-04-26 15:17 UTC by signekb

2024-05-13 08:43 UTC, Aastedet approved these changes

2024-06-19 09:13 UTC, lwjohnst86 requested changes
Just some small edits/clarifications ☺️

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' ICD-8 is the 8th revision of the International Classification of Diseases.
```suggestion
#' ICD-8 is the 8th revision of the International Classification of Diseases.
#' 
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @return n ICD-8 diagnoses as characters.
```suggestion
#' @return A character vector of ICD-8 diagnoses.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @param n The number of ICD-10 diagnoses to generate.
```suggestion
#' @param n The number of ICD-8 or -10 diagnoses to generate.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @param date A date determining whether the diagnoses should be ICD-8 or ICD-10. If null, a random date will be sampled to determine which ICD revision the diagnosis should be from.
```suggestion
#' @param date A date determining whether the diagnoses should be ICD-8 or ICD-10. If null, a random date will be sampled to determine which ICD revision the diagnosis should be from. In the Danish register, ICD-10 is used after 1994.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' #' create_fake_icd(5, "1995-04-19")
```suggestion
#' create_fake_icd(5, "1995-04-19")
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' Create fake ICD 10 diagnoses.
```suggestion
#' Create a vector of random ICD-10 diagnoses.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' ICD-10 is the 10th revision of the International Classification of Diseases.
```suggestion
#' ICD-10 is the 10th revision of the International Classification of Diseases.
#' 
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @param n An integer determining how many diagnoses will be created.
```suggestion
#' @param n An integer determining how many diagnoses to create.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @return n ICD-10 diagnoses as characters.
```suggestion
#' @return A character vector of ICD-10 diagnoses.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' Create fake ATC codes.
```suggestion
#' Create a vector with random ATC codes
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' based on on what organ or system it works on and how it works.
```suggestion
#' based on on what organ or system it works on and how it works.
#' 
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @param n The number of fake ATC codes to generate.
```suggestion
#' @param n The number of random ATC codes to generate.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @return n ATC codes as characters.
```suggestion
#' @return A character vector of ATC codes.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' Create fake dates.
```suggestion
#' Create fake dates
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @return n dates.
```suggestion
#' @return A vector of dates.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' Create padded integers.
```suggestion
#' Create a vector of random zero-padded integers.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @return n NPUs as characters.
```suggestion
#' @return A character vector.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' Create department specialties.
```suggestion
#' Create a vector of random department specialties
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @return n random department specialties.
```suggestion
#' @return A character vector.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' Create drug names from ATC codes.
```suggestion
#' Create a vector of drug names based on a vector of ATC codes
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @return A character with the drug name of the given ATC code.
```suggestion
#' @return A character vector with the drug name of the given ATC code.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' Transform date(s) to the format wwyy.
```suggestion
#' Transform date(s) to the format wwyy
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @return The input date(s) in the format wwyy.
```suggestion
#' @return A vector of dates in the format wwyy.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' Transform date(s) to the format yyyymmdd.
```suggestion
#' Transform date(s) to the format yyyymmdd
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @return The input date(s) in the format yyyymmdd.
```suggestion
#' @return A vector of dates in the format yyyymmdd.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @return A logic. TRUE if the random number is less than the proportion,
```suggestion
#' @return A logic vector. TRUE if the random number is less than the proportion,
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' Insert ATC based on a proportion
```suggestion
#' Insert specific ATC codes based on a proportion
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @param data A tibble
```suggestion
#' @param data A tibble.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' @param data A tibble
```suggestion
#' @param data A tibble.
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +# Insert false positives for Wegovy and Saxenda.
```suggestion
# Insert false positives for Wegovy and Saxenda
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' Insert additional analysis codes for HbA1c.
```suggestion
#' Insert additional analysis codes for HbA1c
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' Add drug names (from ATC codes).
```suggestion
#' Add drug names (from ATC codes)
```

2024-06-19 09:13 UTC, lwjohnst86 commented on data-raw/simulate-data.R
> +#' Simulate data based on simulation definitions.
```suggestion
#' Simulate data based on simulation definitions
```

2024-06-19 12:06 UTC, lwjohnst86 approved these changes

2024-06-19 12:06 UTC, merged

2024-06-19 12:08 UTC, lwjohnst86 commented
Related to your question about `group_split()`. That function has been in experimental state for the last 4 years, so I don't expect it to disappear anytime soon. If these functions were critical to the package, I would change it, but it isn't critical.